version: '2'

services:
  geth:
    build:
      context: .
      dockerfile: ./containers/ethereum/Dockerfile
    mem_limit: 15gb
    cpuset: 0,1,2,3
    volumes:
      - ./data:/root
      - ./containers/ethereum/files/genesis.json:/root/files/genesis.json:ro
    ports:
      - "30303:30303"
      - "8545:8545"
    tty: true

